export const GET_WISHLIST_REQ="GET_WISHLIST_REQ"
export const GET_WISHLIST_SUC="GET_WISHLIST_SUC"
export const GET_WISHLIST_ERR="GET_WISHLIST_ERR"

export const ADD_WISHLIST_REQ="ADD_WISHLIST_REQ"
export const ADD_WISHLIST_SUC="ADD_WISHLIST_SUC"
export const ADD_WISHLIST_ERR="ADD_WISHLIST_ERR"

export const RMV_WISHLIST_REQ="RMV_WISHLIST_REQ"
export const RMV_WISHLIST_SUC="RMV_WISHLIST_SUC"
export const RMV_WISHLIST_ERR="RMV_WISHLIST_ERR"