export const REQ_ADD_ORDER = "REQ_ADD_ORDER"
export const SUCCESS_ADD_ORDER= "SUCCESS_ADD_ORDER"
export const ERR_ADD_ORDER ="ERR_ADD_ORDER"

export const REQ_GET_ORDER = "REQ_GET_ORDER"
export const SUCCESS_GET_ORDER= "SUCCESS_GET_ORDER"
export const ERR_GET_ORDER ="ERR_GET_ORDER"

export const REQ_ALL_ORDER = "REQ_ALL_ORDER"
export const SUCCESS_ALL_ORDER= "SUCCESS_ALL_ORDER"
export const ERR_ALL_ORDER ="ERR_ALL_ORDER"

export const REQ_CANCEL_ORDER = "REQ_CANCEL_ORDER"
export const SUCCESS_CANCEL_ORDER= "SUCCESS_CANCEL_ORDER"
export const ERR_CANCEL_ORDER ="ERR_CANCEL_ORDER"

export const REQ_DOWNLOAD_ORDER = "REQ_DOWNLOAD_ORDER"
export const SUCCESS_DOWNLOAD_ORDER= "SUCCESS_DOWNLOAD_ORDER"
export const ERR_DOWNLOAD_ORDER ="ERR_DOWNLOAD_ORDER"