export const REQ_SIGNUP_USER ="REQ_SIGNUP_USER"
export const SUCCESS_SIGNUP_USER ="SUCCESS_SIGNUP_USER"
export const ERR_SIGNUP_USER ="ERR_SIGNUP_USER"

export const REQ_LOGIN_USER ="REQ_LOGIN_USER"
export const SUCCESS_LOGIN_USER ="SUCCESS_LOGIN_USER"
export const ERR_LOGIN_USER ="ERR_LOGIN_USER"