export const REQ_PRODUCT = "REQ_PRODUCT"
export const GET_PRODUCT = "GET_PRODUCT"
export const ERR_PRODUCT ="ERR_PRODUCT"


export const REQ_ADD_PRODUCT = "REQ_ADD_PRODUCT"
export const SUCCESS_ADD_PRODUCT= "SUCCESS_ADD_PRODUCT"
export const ERR_ADD_PRODUCT ="ERR_ADD_PRODUCT"

export const REQ_UPDATE_PRODUCT = "REQ_UPDATE_PRODUCT"
export const SUCCESS_UPDATE_PRODUCT= "SUCCESS_UPDATE_PRODUCT"
export const ERR_UPDATE_PRODUCT ="ERR_UPDATE_PRODUCT"

export const REQ_DELETE_PRODUCT = "REQ_DELETE_PRODUCT"
export const SUCCESS_DELETE_PRODUCT= "SUCCESS_DELETE_PRODUCT"
export const ERR_DELETE_PRODUCT ="ERR_DELETE_PRODUCT"
